site_name: Calculation documentation

site_url: ""
use_directory_urls: False

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
